### ISSUE TITLE
Enable user authentication

### ISSUE THREAD

**Issue by PovilasKud** [HiromuHota/webspoon-docker#10]
It's a bit unclear were and how should I enable user authentication and management. 

`Security manager

To enable the custom security manager, enable user authentication and add -e CATALINA_OPTS="-Djava.security.manager=org.pentaho.di.security.WebSpoonSecurityManager -Djava.security.policy=/usr/local/tomcat/conf/catalina.policy" to the run command.`

`Edit WEB-INF/web.xml to uncomment/enable user authentication.`

But were should I find that web.xml ?

**Comment by HiromuHota** [comment]
`web.xml` can be found at `$CATALINA_HOME/webapps/spoon/WEB-INF/web.xml` (where `$CATALINA_HOME` points to `/usr/local/tomcat`) within a Docker container.

To edit it, you have three options:
1. After deploying a webSpoon Docker container, login to the container, edit `web.xml`, and restart the container.
2. Download `web.xml` from [here](https://github.com/HiromuHota/pentaho-kettle/blob/webspoon/0.8.1.16/assemblies/static/src/main/resources-filtered/WEB-INF/web.xml) on your Docker host, edit it, and mount this `web.xml` to `$CATALINA_HOME/webapps/spoon/WEB-INF/web.xml` when deploying a webSpoon container.
3. Create your own Dockerfile (based on my Dockerfile-full) that includes `COPY web.xml $CATALINA_HOME/webapps/spoon/WEB-INF/web.xml`, and deploy a webSpoon container using your Dockerfile.

Generally speaking, option 1 is good for a quick test, you will move to 2 then to 3 as your project phase advances (development/test/production).

Please refer to [the last part of my comment here](https://github.com/HiromuHota/webspoon-docker/issues/9#issuecomment-411512673) too, where I describe the same thing in a slightly different level of details.

**Comment by PovilasKud** [comment]
Thank you, problem solved.

**Comment by PovilasKud** [comment]
I'm wondering if there is a way to add some variables to accounts and then later on get those variables in jobs/transformations.

Example account variable **Token** which I could use making REST requests.

**Comment by HiromuHota** [comment]
Interesting use case.

According to [here](https://wiki.pentaho.com/display/EAI/.07+Variables), there are two types of variables: Environment variables and Kettle variables.
Environment variables are too broad, so Kettle variables would be the place to store the authenticated username (e.g., alice) and I could modify webSpoon to do it.

Two questions may arise after becoming able to get the authenticated username.
1. How can you retrieve some variable associated with this username (e.g., token)?
2. Does this ktr file also work on Pentaho Server or Spoon as expected?

For question 1, you may use the Table Input step to query an external database like `select token from users where username=alice`.
For question 2 (more important than 1), do you know if you can get an authenticated user on Pentaho Server or on Spoon in job/trans? If not, I'm not sure if you want to create a ktr file that only works on webSpoon and cannot run on anywhere else.

**Comment by PovilasKud** [comment]
Sorry, for late response.

_1. How can you retrieve some variable associated with this username (e.g., token)?_
I think this step should be left for user to decide. In my case I would get the token making REST client request using Credentials that user used to login to WebSpoon.

_2. Does this ktr file also work on Pentaho Server or Spoon as expected?_
Looking at variables in WebSpoon, I can't find any that holds current username. 
I did a quick search, but couldn't find anything about how to obtain kettle username.

**Comment by HiromuHota** [comment]
I did some research and found that in Spring Security, used by webSpoon for user-auth, `erase-credentials="false"` will prevent the password from being erased and makes it available in a servlet (see [here](https://stackoverflow.com/a/9502533) for details).
This means that username (`HttpServletRequest.getRemoteUser()`) and password (`SecurityContextHolder.getContext().getAuthentication()`) are retrievable and can be set to Kettle variables, which can later be used to make a REST call to an external web service.
From a security point of view though, it would not be a good idea to use the same username&password across different web services (webSpoon and that external web service).

I'm closing this for now, but please feel free to reopen it if you have a better idea.
