### ISSUE TITLE
Filter Rows - cannot delete created condition

### ISSUE THREAD

**Issue by PovilasKud** [HiromuHota/webspoon-docker#12]
In the Filter Rows step documentation it states that to delete condition you need to right-click and press delete.

https://wiki.pentaho.com/display/EAI/Filter+Rows

Popup with delete option doesn't show up on WebSpoon.

Tested on Mac with Firefox and Windows with Chrome with same outcome.

**Comment by HiromuHota** [comment]
Thanks for reporting. I was able to reproduce this issue.
Please do not mind that I copied and created the same issue at HiromuHota/pentaho-kettle/issues/112 for the purpose of house-keeping (this repo is supposed to have only issues related to Dockerized webSpoon).
