### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by PovilasKud** [HiromuHota/webspoon-docker#13]
Is there a place were log files are stored?  
How to enable logging to file?

**Comment by HiromuHota** [comment]
Please refer to https://github.com/HiromuHota/pentaho-kettle/wiki/Admin%3A-Logging.
In Dockerized webSpoon, these log files will be stored at `$CATALINA_HOME/logs`.

**Comment by PovilasKud** [comment]
Thanks, that put me on track!
