### ISSUE TITLE
New version of Pentaho Kettle

### ISSUE THREAD

**Issue by PovilasKud** [HiromuHota/webspoon-docker#14]
Hi, HiromuHota,

You have patched the `Filter Rows` bug [#112](https://github.com/HiromuHota/pentaho-kettle/issues/112) in Pentaho Kettle repository.

I'm wondering how to build a new webspoon image with newest version of **Pentaho Kettle**

**Comment by HiromuHota** [comment]
A nightly build is always available at `hiromuhota/webspoon:nightly-full`.

If you really want to build it yourself,
```
$ git clone git@github.com:HiromuHota/webspoon-docker.git
$ cd webspoon-docker
$ docker build -f ./Dockerfile-full --build-arg version=nightly .
```
