### ISSUE TITLE
Please add some documentation.

### ISSUE THREAD

**Issue by jdlom** [HiromuHota/webspoon-docker#2]
Hi,
I have run the docker command on a server (not localhost) :

`docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -v kettle:/root/.kettle -v pentaho:/root/.pentaho hiromuhota/webspoon:latest-full`

When I access to 192.168.1.99:8080 on my browser, I see the tomcat homepage.

What to do next to launch webspoon ?

Best regards,

**Comment by HiromuHota** [comment]
Please access `http://192.168.1.99:8080/spoon/spoon` in your case (`http://192.168.1.99:8080/spoon` works too).
I'll document this information in this repository later. Thank you for pointing out.

**Comment by jdlom** [comment]
Thank you for the reply. It works like a charm !
