### ISSUE TITLE
Question: Could you do an example of deploying in Kubernetes Cluster?

### ISSUE THREAD

**Issue by kent5440** [HiromuHota/webspoon-docker#25]
I can get it up and running but I cannot create a Repository.
When you click "connect" you get a 403 error.
I am wondering if its because I am using a Reverse Proxy NGINX for the ingress?
Thoughts?
Thanks!

**Comment by kent5440** [comment]
I can get it up and running but I cannot create a Repository.
When you click "connect" you get a "default backend - 404" error.
I am wondering if its because I am using a Reverse Proxy NGINX for the ingress?
Thoughts?
Thanks!

**Comment by HiromuHota** [comment]
I haven't deployed to K8S myself, but you can read a blog post, written by a webSpoon user, about how to do it.
http://diethardsteiner.github.io/pdi/2018/02/03/Webspoon-Kubernetes.html

The reverse proxy might be the problem as webSpoon internally uses a reverse proxy for the Repository dialog (See [here](https://github.com/HiromuHota/pentaho-kettle/issues/36#issuecomment-284550877) for how a reverse proxy is used. The actual implementation uses [HTTP-Proxy-Servlet](https://github.com/HiromuHota/pentaho-kettle/blob/webspoon-8.2/ui/src/main/java/org/pentaho/di/ui/spoon/WebSpoonProxyServlet.java)).
Please open a browser-dev tool and tell me which URL (e.g., `/spoon/osgi/repositories-plugin-core/8.2.0.0-342/index.html`) did the failed HTTP requests try to access.
