### ISSUE TITLE
when trying to run carte using this image it does not work

### ISSUE THREAD

**Issue by tetlika** [HiromuHota/webspoon-docker#27]
I save config in 1.xml (from https://raw.githubusercontent.com/HiromuHota/webspoon-docker/master/slave-server-config.xml) and in /usr/local/tomcat/webapps/spoon do:

./carte.sh 1.xml
#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
Error: Unable to access jarfile /usr/local/tomcat/webapps/spoon/launcher/launcher.jar

**Comment by HiromuHota** [comment]
When you deploy webSpoon, Carte is already there. You don't need to (are not supported to) launch Carte yourself.
Say `http://localhost:8080/spoon/spoon` is your webSpoon web UI, `http://localhost:8080/spoon/kettle` is Carte.
