### ISSUE TITLE
Is it possible to run the image with UI in different language ?

### ISSUE THREAD

**Issue by kuwii** [HiromuHota/webspoon-docker#28]
Currently when I run image and open webspoon in browser, the UI is in English. So I wonder if its possible to get an interface in other language, for example, Chinese.
Thanks.

**Comment by HiromuHota** [comment]
Yes it is possible, but you cannot change language from UI.

Create a file like below at `/home/tomcat/.kettle/.languageChoice` for Simplified Chinese and restart the container.
```
LocaleDefault=zh_CN
LocaleFailover=en_US
```

**Comment by kuwii** [comment]
Thanks for help, I've successfully changed the language.

**Comment by tlw-ray** [comment]
Maybe the path is /root/.kettle/.languageChoice ?

**Comment by HiromuHota** [comment]
It used to be `/root/.kettle/.languageChoice` for 0.8.2.18 and lower.
It actually is `~/.kettle/.languageChoice`, so depending on the user who runs Tomcat.
I changed the user from root to tomcat for a security reason at 0.8.2.19.
Thus, `/root/.kettle/.languageChoice` for 0.8.2.18 and lower, `/home/tomcat/.kettle/.languageChoice` for 0.8.2.19 and higher.

The above is valid only when you use the Docker images that I created.
If you deploy webSpoon without Docker or build a Docker image yourself, the path might be different.

**Comment by tlw-ray** [comment]
Yes, it is. Thanks!

**Comment by yuanxuzhang** [comment]
> It used to be `/root/.kettle/.languageChoice` for 0.8.2.18 and lower.
> It actually is `~/.kettle/.languageChoice`, so depending on the user who runs Tomcat.
> I changed the user from root to tomcat for a security reason at 0.8.2.19.
> Thus, `/root/.kettle/.languageChoice` for 0.8.2.18 and lower, `/home/tomcat/.kettle/.languageChoice` for 0.8.2.19 and higher.
> 
> The above is valid only when you use the Docker images that I created.
> If you deploy webSpoon without Docker or build a Docker image yourself, the path might be different.

How to set the langguage path, when deloy webSpoon?

**Comment by HiromuHota** [comment]
You cannot specify the path of `.languageChoice`.
Like I said, it is always `~/.kettle/.languageChoice` no matter what.

The changing part is `~/`, which depends on who runs the Tomcat.
If you use root, it'd be `/root/.kettle/.languageChoice`.
If you use non-root user like ubuntu, it'd be `/home/ubuntu/.kettle/.languageChoice`.
