### ISSUE TITLE
 How to use KettleDatabaseRepository

### ISSUE THREAD

**Issue by chenshangge** [HiromuHota/webspoon-docker#30]
How to use KettleDatabaseRepository

**Comment by HiromuHota** [comment]
Please see [here](https://help.pentaho.com/Documentation/7.1/0L0/0Y0/040#Database_Repository) and [there](https://forums.pentaho.com/threads/231355-PDI-8-2-CE-How-to-create-a-database-repository/).

**Comment by chenshangge** [comment]
but I can not find the action in WebSpoon

**Comment by chenshangge** [comment]
3q
