### ISSUE TITLE
How to schedule job execution?

### ISSUE THREAD

**Issue by willsilvano** [HiromuHota/webspoon-docker#31]
Hi, @HiromuHota.

First, thanks for this awesome project.

I'm using the webspoon-docker in my production project, but I need to automatize the execution of my job.

I've tried to schedule the START component, but if my container of spoon restart this schedule don't work anymore, then I need to play the job again.

Searching at Google, I've found some articles where people say to use kitchen.sh or pan.sh, but these files doesn't work in webspoon-docker, right?

I'm trying to automatize the steps with Selenium and then to use Kubernetes cron to schedule these steps to execute my job.

There is any way simplest to do this automation?

**Comment by HiromuHota** [comment]
webSpoon does not have kitchen.sh or pan.sh, but includes Carte.
The endpoint is at `http://localhost:8080/spoon/kettle` (if webSpoon is deployed at `http://localhost:8080/spoon/spoon`).
You can start a trans/job using the Carte APIs (https://help.pentaho.com/Documentation/8.2/Developer_Center/REST_API/Carte).
Unfortunately, Carte does not have a scheduler. Use Cron or something for scheduling.
Hope this helps.

**Comment by willsilvano** [comment]
Hi, thanks.

When I go to route /spoon/kettle:

```
java.lang.NullPointerException
	org.pentaho.di.www.CarteServlet.doGet(CarteServlet.java:74)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
```
I forgot to set something up?

**Comment by willsilvano** [comment]
I read the documentation you mentioned above and was able to run the job through the URL: 

http://localhost:8080/spoon/kettle/executeJob/?job=/home/tomcat/.kettle/data/myJob.kjb&level=Debug

Thanks!!

**Comment by willsilvano** [comment]
When I do loggin throught Browser, and after call the API it works.
But when I restart spoon and call the API again:

```
ERROR (version 8.3.0.0-371-20, build 8.3.0.0-371-20 from 2019-11-21 12.13.39 by jenkins) : Unable to find datasource by JNDI name: smart_master
guidoo-bi-spoon          | 2020/01/06 18:02:26 - Smart_Master - ERROR (version 8.3.0.0-371-20, build 8.3.0.0-371-20 from 2019-11-21 12.13.39 by jenkins) : org.pentaho.di.core.database.DataSourceNamingException: 
guidoo-bi-spoon          | 2020/01/06 18:02:26 - Smart_Master - javax.naming.NameNotFoundException: Name [smart_master] is not bound in this Context. Unable to find [smart_master].
guidoo-bi-spoon          | 2020/01/06 18:02:26 - Smart_Master - Name [smart_master] is not bound in this Context. Unable to find [smart_master].
``` 

I put the connection configurations here: /usr/local/tomcat/simple-jndi/jdbc.properties

Need any extra configuration?

**Comment by HiromuHota** [comment]
I think the current implementation behaves like this:
When the first session of webSpoon starts, (web)Spoon loads JNDI connections from `/usr/local/tomcat/simple-jndi/jdbc.properties` and then Carte can use the loaded connections.
So, if you ever open webSpoon after restart, I think Carte can use the JNDI connections loaded by (web)Spoon.
Let me know if this works.

If you don't want to open webSpoon every time you restart the Tomcat, you'd have to define the JNDI connection in `webapps/spoon/WEB-INF/web.xml` and `webapps/spoon/META-INF/context.xml` for Carte.
https://help.pentaho.com/Documentation/8.3/Setup/Set_up_JNDI_connections_for_the_Pentaho_Server

**Comment by HiromuHota** [comment]
As mentioned [here](https://forums.pentaho.com/threads/166585-JNDI-CARTE-and-SPOON/?p=380700#post380700),
> Spoon don't have real JNDI since it is not a web server but a simple JNDI.
Carte is a Jetty web server, so Carte JNDI is a question of Jetty JNDI, since Carte is a jetty web server under the hood. (have never try JNDI with Carte).

The Tomcat document https://tomcat.apache.org/tomcat-8.5-doc/jndi-datasource-examples-howto.html may also help.

**Comment by HiromuHota** [comment]
Now I think that webSpoon should also use "real" JNDI instead of "simple" JNDI.

According to https://github.com/h-thurow/Simple-JNDI,
> Simple-JNDI is intended to solve two problems. The first is to test or use classes that depend on JNDI environment objects (most known a DataSource) provided by a Java EE container outside of such a container.

webSpoon runs inside a servlet container like Tomcat and so does Carte.
Therefore, webSpoon can (maybe should) use the JNDI provided by Tomcat.

**Comment by willsilvano** [comment]
Yes, inside `/usr/local/tomcat/simple-jndi/jdbc.properties` I put the database configs I need.
The problem is when I call  the API directly it don't recognize the JNDI configs, but if I loggin in SPOON and after call the API again it worked.
I also made a POST request on the SPOON login form but it still didn't work.

**Comment by HiromuHota** [comment]
Thank you for your confirmation.

A single POST call may not be enough for webSpoon to load simple JNDI configs.
Instead, you could use Google Chrome in the head-less mode to do this.

Or please define "real" JNDI instead of "simple" one.

**Comment by willsilvano** [comment]
I changed it to use connection instead of JNDI.

The connection I set through kettle environment variables like this:

```
<connection>
    <name>MyConnection</name>
    <server>${HOST}</server>
    <type>MYSQL</type>
    <access>Native</access>
    <database>${DATABASE}</database>
    <port>3306</port>
    <username>${USER}</username>
    <password>${PASSWORD}</password>
</connection>
```

It works now. 

Thank you for your help!
