### ISSUE TITLE
¿how restart client after install plugins?...

### ISSUE THREAD

**Issue by IvanSparrow** [HiromuHota/webspoon-docker#33]
Hi,

I have the following doubt, after installing plugins from the marketplace, I must restart the client, but it does not work for me, what steps do you recommend to do this, modify the docker image?

Thanks in advance, greetings ...

**Comment by HiromuHota** [comment]
You just have to restart the Tomcat instead of reloading the tab/window on browser.

**Comment by IvanSparrow** [comment]
thank you for the answer, finally have problem with the kubernetes.
