### ISSUE TITLE
Repository Connect Button Not Visiable in 9.0 WebSpoon

### ISSUE THREAD

**Issue by penske-boranna** [HiromuHota/webspoon-docker#35]
Hi Team,

I'm running into some isssue related to Webspoon "Connet" Button not visiable after webspoon restart. Sometime the button is visable. But most of the time is not visable and also the marketplace is option is also disabled.

System Details:
OS: Cent OS 7
tomcat 8 
Webspoon 9
export version=0.9.0.21
export dist=9.0.0.0-423

![image](https://user-images.githubusercontent.com/38040898/80236170-67916200-8678-11ea-8dfa-1475d9729d2c.png)

**Comment by penske-boranna** [comment]
Marketplace is also disabled.

![image](https://user-images.githubusercontent.com/38040898/80236789-49783180-8679-11ea-94e6-dac4d6df0991.png)

**Comment by HiromuHota** [comment]
How did you deploy webSpoon?
Docker or non-Docker?

**Comment by penske-boranna** [comment]
it is non-Docekr install

**Comment by gboranna** [comment]
Hi Hota-san

If you are avaliable I can walk you through the issue. 

join team meeting

https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWRjZjUwZjEtNTU5OC00YzhiLTlhMTEtZjA5ZjdiM2E5M2U1%40thread.v2/0?context=%7b%22Tid%22%3a%22231dd9cd-ddc7-4fba-ae78-9f4ac3c912e7%22%2c%22Oid%22%3a%22297cab45-ae06-40ca-89d8-067938daa609%22%7d

**Comment by HiromuHota** [comment]
Please remove the Karaf cache and restart the Tomcat.
```
$ rm -rf system/karaf/caches/
```

**Comment by penske-boranna** [comment]
I did remove the Karaf cache folder. Not much of help.

**Comment by penske-boranna** [comment]
Also tried these steps.

- Add the following -D Parameters to JAVA_OPTs variable:
-Dpentaho.karaf.root.copy.dest.folder=$PENTAHO_KARAF_ROOT
-Dpentaho.karaf.root.transient=false

Note: Although these instructions say to set '-Dpentaho.karaf.root.transient=false', if that doesn't work then try it set to true instead. Although I am finding that most instances of this issue are fixed by setting it to false, I found some people reporting that setting it to true fixed this. By doing this, the karaf folder should be cleared every time Spoon is starting, meaning that you won't have to manually clear the karaf caches to see the connect button.

**Comment by HiromuHota** [comment]
Can you paste the copy of `logs/catalina.out`?

**Comment by penske-boranna** [comment]
24-Apr-2020 17:34:01.199 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.23
24-Apr-2020 17:34:01.202 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 28 2017 10:30:11 UTC
24-Apr-2020 17:34:01.202 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.23.0
24-Apr-2020 17:34:01.202 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-1062.18.1.el7.x86_64
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_242-b08
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/webspoon-home/tomcat
24-Apr-2020 17:34:01.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/webspoon-home/tomcat
24-Apr-2020 17:34:01.204 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/webspoon-home/tomcat/conf/logging.properties
24-Apr-2020 17:34:01.204 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
24-Apr-2020 17:34:01.204 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1024m
24-Apr-2020 17:34:01.204 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx8192m
24-Apr-2020 17:34:01.204 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xss228k
24-Apr-2020 17:34:01.204 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
24-Apr-2020 17:34:01.205 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
24-Apr-2020 17:34:01.205 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
24-Apr-2020 17:34:01.205 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/webspoon-home/tomcat
24-Apr-2020 17:34:01.205 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/webspoon-home/tomcat
24-Apr-2020 17:34:01.205 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/webspoon-home/tomcat/temp
24-Apr-2020 17:34:01.205 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
24-Apr-2020 17:34:01.281 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
24-Apr-2020 17:34:01.297 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
24-Apr-2020 17:34:01.300 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
24-Apr-2020 17:34:01.301 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
24-Apr-2020 17:34:01.302 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 500 ms
24-Apr-2020 17:34:01.326 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
24-Apr-2020 17:34:01.326 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.23
24-Apr-2020 17:34:01.355 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/webspoon-home/tomcat/webapps/spoon.war]
24-Apr-2020 17:34:14.852 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
24-Apr-2020 17:34:14.878 INFO [localhost-startStop-1] org.pentaho.di.ui.spoon.WebSpoonServletContextListener.contextInitialized Current directory: /opt/webspoon-home/tomcat/bin
24-Apr-2020 17:34:15.165 INFO [localhost-startStop-1] org.pentaho.di.ui.spoon.WebSpoonServletContextListener.contextInitialized  Error reading information from resource /opt/webspoon-home/tomcat/bin/system/kettle/slave-server-config.xml (No such file or directory) 
24-Apr-2020 17:35:57.495 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/webspoon-home/tomcat/webapps/spoon.war] has finished in [116,139] ms
24-Apr-2020 17:35:57.495 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/webspoon-home/tomcat/webapps/ROOT]
24-Apr-2020 17:35:57.510 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
24-Apr-2020 17:35:57.512 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/webspoon-home/tomcat/webapps/ROOT] has finished in [17] ms
24-Apr-2020 17:35:57.516 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
24-Apr-2020 17:35:57.526 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
24-Apr-2020 17:35:57.528 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 116226 ms
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint

**Comment by HiromuHota** [comment]
I've notice that 
> Current directory: /opt/webspoon-home/tomcat/bin

The current directory should be `/opt/webspoon-home/tomcat`.

I wonder how you start Tomcat.
I'd suggest to start it as

```
$ cd /opt/webspoon-home/tomcat
$ ./bin/startup.sh
```

**Comment by penske-boranna** [comment]
i'm starting serving using the same commands 

$ cd /opt/webspoon-home/tomcat
$ ./bin/startup.sh

**Comment by penske-boranna** [comment]
Followed below steps and now after multiple restart the issue resolved. But now running into a different issue.

Steps followed to resolve the reported issue.
$ cd $CATALINA_HOME
$ rm -rf work 
$ rm -rf temp 
$ rm -rf $CATALINA_HOME/system/karaf

Go to downloads 
$ unzip pdi-ce-9.0.0.0-423.zip
$ cd data-integration
cp -r ~/data-integration/system/karaf  $CATALINA_HOME/system


$ cd $CATALINA_HOME
$ ./bin/startup.sh

Now running into new issue 
https://github.com/HiromuHota/pentaho-kettle/issues/202
